# Generated by Django 2.1.4 on 2019-03-14 11:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190314_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body_de',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
