sudo: true
before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
language: python
services:
  - postgresql
env:
  - DJANGO_SETTINGS_MODULE=config.settings.test
install:
  - pip install -r requirements/local.txt
script:
  - coverage run manage.py test
after_success:
  - coveralls
notifications:
  email:
    - merlin.buczek@gmail.com
python:
  - "3.7"
