# Generated by Django 2.0.13 on 2019-05-25 13:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('preview', models.TextField(blank=True, verbose_name='preview')),
                ('preview_en', models.TextField(blank=True, null=True, verbose_name='preview')),
                ('preview_de', models.TextField(blank=True, null=True, verbose_name='preview')),
                ('body', wagtail.core.fields.RichTextField(verbose_name='content')),
                ('body_en', wagtail.core.fields.RichTextField(null=True, verbose_name='content')),
                ('body_de', wagtail.core.fields.RichTextField(null=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'News entry',
                'verbose_name_plural': 'News entries',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
            bases=('wagtailcore.page',),
        ),
    ]
