# Generated by Django 2.2.1 on 2019-05-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsentry',
            name='side_content',
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='preview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='preview_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='preview_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
