# Generated by Django 2.2.1 on 2019-05-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'News Blog', 'verbose_name_plural': 'News Blogs'},
        ),
    ]
