# Generated by Django 2.2.1 on 2019-05-28 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190525_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2019, 5, 28), verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
