# Generated by Django 2.2.1 on 2019-06-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='show_all',
            field=models.BooleanField(default=False),
        ),
    ]
