# Generated by Django 2.2.1 on 2019-06-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newspage_show_all'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsentry',
            options={'ordering': ['-date'], 'verbose_name': 'news entry', 'verbose_name_plural': 'news entries'},
        ),
    ]
