# Generated by Django 2.2.1 on 2019-06-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190605_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'news blog', 'verbose_name_plural': 'news blogs'},
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='post date'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='show_all',
            field=models.BooleanField(default=False, help_text='Include all news from subpages', verbose_name='show all news'),
        ),
    ]
