# Generated by Django 2.2.2 on 2019-06-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190613_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='show_all',
        ),
    ]
