# Generated by Django 2.2.2 on 2019-06-15 09:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newspage_show_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsentry',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='body_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
