# Generated by Django 2.2.4 on 2019-09-03 15:51

from django.db import migrations
import mpicms.base.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20190818_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsentry',
            name='body',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', mpicms.base.blocks.TableBlock(label='Table'))], blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='body_de',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', mpicms.base.blocks.TableBlock(label='Table'))], blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='body_en',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', mpicms.base.blocks.TableBlock(label='Table'))], blank=True, null=True, verbose_name='content'),
        ),
    ]
