# Generated by Django 2.2.4 on 2019-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20190909_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='show_in_main_news',
            field=models.BooleanField(default=False),
        ),
    ]
