# Generated by Django 2.2.4 on 2019-09-11 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_newsentry_show_in_main_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsentry',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
