# Generated by Django 2.2.4 on 2019-09-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20190911_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='show_toc',
            field=models.BooleanField(default=True, verbose_name='Show table of content'),
        ),
    ]
