# Generated by Django 2.2.4 on 2019-09-05 09:18

from django.db import migrations, models
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', wagtail.core.fields.RichTextField(verbose_name='text')),
                ('groups', wagtail.core.fields.RichTextField(verbose_name='text')),
                ('authors', wagtail.core.fields.RichTextField(verbose_name='text')),
                ('source', wagtail.core.fields.RichTextField(verbose_name='text')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='Digital Object Identifier')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
