# Generated by Django 2.2.1 on 2019-06-01 11:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('description_en', models.TextField(blank=True, max_length=400, null=True)),
                ('description_de', models.TextField(blank=True, max_length=400, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True, verbose_name='content')),
                ('body_en', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='content')),
                ('body_de', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='content')),
            ],
            options={
                'ordering': ['start_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
