# Generated by Django 2.2.1 on 2019-06-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190601_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventindex',
            options={'verbose_name': 'event index', 'verbose_name_plural': 'event indexes'},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_de',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
