# Generated by Django 2.2.2 on 2019-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190624_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_en',
        ),
    ]
