# Generated by Django 2.2.2 on 2019-06-25 15:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20190625_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, editable=False, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(editable=False, max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='room',
            field=models.CharField(blank=True, editable=False, max_length=25, verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='contactgroups',
            name='contact',
            field=modelcluster.fields.ParentalKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='personal.Contact'),
        ),
        migrations.AlterField(
            model_name='contactgroups',
            name='group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='personal.Group', verbose_name='groups'),
        ),
    ]
