# Generated by Django 2.2.2 on 2019-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20190625_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(related_name='members', to='personal.Group'),
        ),
        migrations.DeleteModel(
            name='ContactGroups',
        ),
    ]
