# Generated by Django 2.2.2 on 2019-06-25 16:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20190625_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='groups',
        ),
        migrations.CreateModel(
            name='ContactGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('contact', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='personal.Contact')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='personal.Group', verbose_name='groups')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
