# Generated by Django 2.2.2 on 2019-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20190625_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ManyToManyField(related_name='members', to='personal.Group'),
        ),
        migrations.DeleteModel(
            name='ContactGroups',
        ),
    ]
