# Generated by Django 2.2.2 on 2019-06-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20190625_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='group',
            new_name='groups',
        ),
    ]
