# Generated by Django 2.2.2 on 2019-07-03 15:53

from django.db import migrations
import django.db.models.deletion
import mpicms.personal.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20190703_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroups',
            name='contact',
            field=mpicms.personal.models.FilterableParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='personal.Contact'),
        ),
    ]
