# Generated by Django 2.2.2 on 2019-07-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_auto_20190709_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_de', models.CharField(max_length=50, null=True, verbose_name='title')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='position',
        ),
    ]
