# Generated by Django 2.2.2 on 2019-07-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20190710_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.Position', verbose_name='position'),
        ),
    ]
