# Generated by Django 2.2.2 on 2019-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_contact_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name_de',
            field=models.CharField(max_length=254, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(max_length=254, null=True, verbose_name='name'),
        ),
    ]
