# Generated by Django 2.2.2 on 2019-07-29 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_auto_20190712_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-priority', 'last_name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-priority'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Priority from 0-999 to determine the sorting order.', null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='group',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Priority from 0-99 to determine the sorting order.', null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='priority'),
        ),
    ]
