# Generated by Django 2.2.2 on 2019-07-29 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_auto_20190729_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Priority from 0-999 to determine the sorting order.', validators=[django.core.validators.MaxValueValidator(99)], verbose_name='priority'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Priority from 0-99 to determine the sorting order.', validators=[django.core.validators.MaxValueValidator(99)], verbose_name='priority'),
            preserve_default=False,
        ),
    ]
