# Generated by Django 2.2.2 on 2019-07-29 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_auto_20190729_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Priority from 0-999 to determine the sorting order.', validators=[django.core.validators.MaxValueValidator(999)], verbose_name='priority'),
        ),
    ]
