# Generated by Django 2.2.4 on 2019-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0024_auto_20190902_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(default='', max_length=254, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_de',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_en',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='name'),
        ),
    ]
