# Generated by Django 2.2.1 on 2019-05-10 11:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='body_de',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
