# Generated by Django 2.2.1 on 2019-05-25 14:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypage',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'homepage', 'verbose_name_plural': 'homepages'},
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='body_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='side_content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Information displayed on the page in the sidebar', verbose_name='sidebar content'),
        ),
    ]
