# Generated by Django 2.2.1 on 2019-05-14 11:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190514_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='body_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
