# Generated by Django 2.2.1 on 2019-05-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('base', '0002_auto_20190525_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='contact',
            field=models.ManyToManyField(related_name='categories', to='personal.Person'),
        ),
    ]
