# Generated by Django 2.2.1 on 2019-05-14 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0003_auto_20190514_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPage',
            new_name='CategoryPage',
        ),
    ]
