# Generated by Django 2.2.1 on 2019-05-15 15:43

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190514_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='body_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
