# Generated by Django 2.2.1 on 2019-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190527_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
