# Generated by Django 2.2.1 on 2019-05-17 12:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190515_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='side_content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
