# Generated by Django 2.2.1 on 2019-05-17 12:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_categorypage_side_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='side_content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
