# Generated by Django 2.2.1 on 2019-05-17 12:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190517_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='side_content',
            field=wagtail.core.fields.StreamField([('information', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('content', wagtail.core.blocks.TextBlock())], icon='text'))]),
        ),
    ]
