# Generated by Django 2.2.1 on 2019-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_wikipage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='preview',
            field=models.TextField(blank=True, verbose_name='preview'),
        ),
    ]
