# Generated by Django 2.2.1 on 2019-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_categorypage_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='preview_de',
            field=models.TextField(blank=True, null=True, verbose_name='preview'),
        ),
        migrations.AddField(
            model_name='categorypage',
            name='preview_en',
            field=models.TextField(blank=True, null=True, verbose_name='preview'),
        ),
    ]
