# Generated by Django 2.2.1 on 2019-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190605_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
