# Generated by Django 2.2.1 on 2019-05-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('base', '0010_auto_20190519_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamPage',
        ),
    ]
