# Generated by Django 2.2.1 on 2019-06-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20190607_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('position', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'contact information',
                'verbose_name_plural': 'contact information',
            },
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
