# Generated by Django 2.2.1 on 2019-06-13 11:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20190613_1333'),
        ('base', '0013_auto_20190613_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrelation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_references', to='personal.Contact', verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='contactrelation',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='base.CategoryPage'),
        ),
    ]
