# Generated by Django 2.2.2 on 2019-06-15 09:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20190613_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='body_de',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
