# Generated by Django 2.2.2 on 2019-06-18 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0015_auto_20190615_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='RootPage',
        ),
        migrations.AlterModelOptions(
            name='rootpage',
            options={'verbose_name': 'root page', 'verbose_name_plural': 'root pages'},
        ),
    ]
