# Generated by Django 2.2.2 on 2019-06-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20190618_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='preview_de',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='preview_en',
        ),
    ]
