# Generated by Django 2.2.2 on 2019-06-24 11:58

from django.db import migrations
import mpicms.base.blocks
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20190624_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Table'))], blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_de',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Table'))], blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Table'))], blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='body',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Table'))], blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='body_de',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Table'))], blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(label='Editor')), ('markdown', mpicms.base.blocks.MarkdownBlock(label='Raw Markdown')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Table'))], blank=True, null=True, verbose_name='content'),
        ),
    ]
