# Generated by Django 2.2.2 on 2019-07-03 14:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20190624_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(features=['h4', 'h5', 'h6', 'bold', 'italic', 'link', 'document-link'], label='Editor')), ('contacts', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('personal.Contact', label='Contact')))], blank=True, verbose_name='sidebar content'),
        ),
    ]
