# Generated by Django 2.2.2 on 2019-07-12 10:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20190709_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootpage',
            name='footer_items',
            field=wagtail.core.fields.StreamField([('Menu', wagtail.core.blocks.StructBlock([('Title', wagtail.core.blocks.CharBlock()), ('Items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('Title', wagtail.core.blocks.CharBlock()), ('URL', wagtail.core.blocks.URLBlock())])))], icon='list-ul'))], blank=True),
        ),
    ]
