# Generated by Django 2.2.2 on 2019-07-12 10:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20190712_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootpage',
            name='footer_items',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())])))], icon='list-ul'))], blank=True),
        ),
    ]
