# Generated by Django 2.2.2 on 2019-07-12 10:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20190712_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootpage',
            name='footer_items_de',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())])))], icon='list-ul'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rootpage',
            name='footer_items_en',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())])))], icon='list-ul'))], blank=True, null=True),
        ),
    ]
