# Generated by Django 2.2.2 on 2019-07-12 10:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20190712_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootpage',
            name='banner',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link']))], icon='warning'))], blank=True),
        ),
    ]
