# Generated by Django 2.2.2 on 2019-07-12 11:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20190712_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('editor', wagtail.core.blocks.RichTextBlock(features=['h4', 'h5', 'h6', 'bold', 'italic', 'link', 'document-link'], label='Editor')), ('contacts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('contact', wagtail.snippets.blocks.SnippetChooserBlock('personal.Contact', label='Contact')), ('information', wagtail.core.blocks.TextBlock(label='Information', required=False))]), icon='user', label='Contacts', template='base/blocks/contact_block.html'))], blank=True, verbose_name='Sidebar Content'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidebar_de',
            field=wagtail.core.fields.StreamField([('editor', wagtail.core.blocks.RichTextBlock(features=['h4', 'h5', 'h6', 'bold', 'italic', 'link', 'document-link'], label='Editor')), ('contacts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('contact', wagtail.snippets.blocks.SnippetChooserBlock('personal.Contact', label='Contact')), ('information', wagtail.core.blocks.TextBlock(label='Information', required=False))]), icon='user', label='Contacts', template='base/blocks/contact_block.html'))], blank=True, null=True, verbose_name='Sidebar Content'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidebar_en',
            field=wagtail.core.fields.StreamField([('editor', wagtail.core.blocks.RichTextBlock(features=['h4', 'h5', 'h6', 'bold', 'italic', 'link', 'document-link'], label='Editor')), ('contacts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('contact', wagtail.snippets.blocks.SnippetChooserBlock('personal.Contact', label='Contact')), ('information', wagtail.core.blocks.TextBlock(label='Information', required=False))]), icon='user', label='Contacts', template='base/blocks/contact_block.html'))], blank=True, null=True, verbose_name='Sidebar Content'),
        ),
        migrations.AlterField(
            model_name='rootpage',
            name='banner',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', max_length=200, required=False)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link'], label='Text'))], icon='warning', label='Banner'))], blank=True, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='rootpage',
            name='footer_items',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('url', wagtail.core.blocks.URLBlock(label='URL'))], label='Items')))], icon='list-ul', label='menu'))], blank=True, verbose_name='Footer Items'),
        ),
        migrations.AlterField(
            model_name='rootpage',
            name='footer_items_de',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('url', wagtail.core.blocks.URLBlock(label='URL'))], label='Items')))], icon='list-ul', label='menu'))], blank=True, null=True, verbose_name='Footer Items'),
        ),
        migrations.AlterField(
            model_name='rootpage',
            name='footer_items_en',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('url', wagtail.core.blocks.URLBlock(label='URL'))], label='Items')))], icon='list-ul', label='menu'))], blank=True, null=True, verbose_name='Footer Items'),
        ),
    ]
