# Generated by Django 2.2.2 on 2019-07-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20190723_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredimage',
            options={'verbose_name': 'featured image', 'verbose_name_plural': 'featured images'},
        ),
    ]
