# Generated by Django 2.2.4 on 2019-09-11 07:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20190911_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootpage',
            name='footer_items',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('url', wagtail.core.blocks.URLBlock(label='URL'))], label='Items')))]))], blank=True, verbose_name='Footer Items'),
        ),
        migrations.AlterField(
            model_name='rootpage',
            name='footer_items_de',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('url', wagtail.core.blocks.URLBlock(label='URL'))], label='Items')))]))], blank=True, null=True, verbose_name='Footer Items'),
        ),
        migrations.AlterField(
            model_name='rootpage',
            name='footer_items_en',
            field=wagtail.core.fields.StreamField([('menu', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('url', wagtail.core.blocks.URLBlock(label='URL'))], label='Items')))]))], blank=True, null=True, verbose_name='Footer Items'),
        ),
    ]
